name: CI Toracon Page

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
      # Install prettier
      - name: Install prettier with Node.js
        run: npm install --save-dev --save-exact prettier
      # Prettify code
      - name: Run prettier command
        run: npm run prettier

